version: "3"
services:
  api:
    build:
      context: .
    image: local/mock_services:dev
    command: flask-server
    # restart: always
    ports:
      - 5000:5000
    volumes:
      - "./mock_services:/app/mock_services:ro"
      - "./profiles:/app/profiles:ro"
