---
swagger: "2.0"
info: {"title": "Profile"}
produces: ["application/json"]
consumes: ["application/json"]
scheme: ["http", "https"]
tags:
    - name: profile
      description: управление поведением сервиса

paths:

    /mock_profile:
        get:
            tags: [profile]
            operationId: profile.get_profile
            summary: получить профиль
            responses:
                200:
                    description: OK
                    schema:
                        $ref: '#/components/schemas/ProfileConfig'

        post:
            tags: [profile]
            operationId: profile.set_profile
            summary: загрузить профиль в память сервера
            parameters:
            - in: body
              schema:
                $ref: '#/components/schemas/ProfileConfig'
            responses:
                200:
                    description: OK

        delete:
            tags: [profile]
            operationId: profile.delete_profile
            summary: удалить профиль из памяти сервера
            responses:
                200:
                    description: OK

components:

    schemas:

        ProfileEndpoint:
            type: string
            example: easysms.send_sms

        ProfileFakeResponse:
            type: object
            properties:
                endpoint:
                    $ref: '#/components/schemas/ProfileEndpoint'
                status:
                    summary: статус ответа
                    type: integer
                    example: 200
                content_type:
                    type: string
                    default: application/json
                    required: false
                    summary: mime type ответа
                body_template:
                    type: string
                    summary: ответ
                    example: |
                       { "message": "hello from server" }
                step:
                    type: integer
                    summary: шаг ответа
                    default: 0
                chance:
                    type: integer
                    summary: шанс ответа на текущем шаге
                    required: false
                    default: 100

        ProfileConfig:
            type: array
            items:
                $ref: '#/components/schemas/ProfileFakeResponse'
